Emg changes
harbour/core pull request #329
Opened 2023-10-29 13:28 UTC by EMG60

Support for Openssl 3

2023-10-31 10:18 UTC, tuffnatty commented
@EMG60 Thanks! But now it looks like the line ending encoding in ChangeLog.txt has changed, that is, every line of the file is considered as modified. Please try to minimise unnecessary changes so that the remaining ones can be easily reviewed.

2023-10-31 11:10 UTC, EMG60 commented
Il 31/10/2023 11:18, Phil Krylov ha scritto:

> @EMG60 <https://github.com/EMG60> Thanks! But now it looks like the line 
> ending encoding in ChangeLog.txt has changed, that is, every line of the 
> file is considered as modified. Please try to minimise unnecessary 
> changes so that the remaining ones can be easily reviewed.

Fixed. Please check now.

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

2023-10-31 11:20 UTC, tuffnatty commented
@EMG60 It's much better now! But UTF-8 characters are corrupted in ChangeLog.txt.

2023-10-31 11:53 UTC, EMG60 commented
Il 31/10/2023 12:21, Phil Krylov ha scritto:

> @EMG60 <https://github.com/EMG60> It's much better now! But UTF-8 
> characters are corrupted in ChangeLog.txt.

Recheck now and let me know.

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

2023-11-04 12:34 UTC, EMG60 commented
Still waiting... :-)

2023-11-04 13:59 UTC, tuffnatty commented
@EMG60 Looks good now! I would merge it if I could test it. Unfortunately, I am missing a Windows test environment.

2023-11-04 14:03 UTC, EMG60 commented
So, what do I have to do now? I am near to give up. Is Harbour still an 
active project?

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

2023-11-04 14:06 UTC, EMG60 commented
Anyway, I already tested it building Harbour for MSC32, MSC64, BCC32, 
BCC64, MGW32 and MGW64. Is it not enough? Here they are the packages:

https://github.com/FiveTechSoft/harbour_and_xharbour_builds/blob/master/README.md

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

2023-11-04 14:23 UTC, tuffnatty requested changes

2023-11-04 14:23 UTC, tuffnatty commented on ChangeLog.txt
> +  * contrib\hbssl\hbssl,hbp
please replace backslashes with forward slashes, and comma with dot.

2023-11-04 14:25 UTC, tuffnatty commented
Thanks for your patience! If you have tested the Windows builds, I am going to merge this as soon as you fix the minor typos in Changelog.

2023-11-04 15:16 UTC, EMG60 commented
Ops! Sorry. Fixed.

2023-11-04 15:38 UTC, merged

2023-11-04 15:55 UTC, EMG60 commented
Thank you! :-)

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg