Fixed bcc.mk and hbmk2.prg for BCC64
harbour/core pull request #330
Opened 2023-11-04 16:15 UTC by EMG60

2023-11-04 20:10 UTC, tuffnatty requested changes

2023-11-04 20:10 UTC, tuffnatty commented on config/win/bcc.mk
> +   LD_RULE = $(LD) $(LDFLAGS) $(HB_LDFLAGS) $(HB_USER_LDFLAGS) c0x64$(OBJ_EXT) $(filter-out %$(RES_EXT),$(^F)), "$(subst /,$(BACKSLASH),$(BIN_DIR)/$@)", nul, $(LDLIBS) cw64mt import64 xmath,, $(filte
It seems the code for `_isnanl` and `_finitel` is not included. I believe it belongs to src/common/hbprintf.c.

2023-11-04 22:54 UTC, EMG60 commented
Sorry, but the switches you are proposing are not correct. Even the 
existing ones for BCC32 are wrong (ie. -w-sig- and the others) because 
the right syntax is -w-sig, without the last minus sign.

In BCC64 the switch -Weverything is absolutely useless due to the tons 
of warning from the BCC64 include files. Anyway, BCC32 compiles fine so 
I would not touch it. For BCC64 I choosen what allow the compilation 
without tones of lines of warnings. But if you really want this I can 
put your suggested switches, no problems for me. So please confirm that 
it is what you want.

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

2023-11-04 22:58 UTC, EMG60 commented
> It seems the code for |_isnanl| and |_finitel| is not included. I 
> believe it belongs to src/common/hbprintf.c.

So, what do you want me to do exactly? I don't understand.

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

2023-11-05 07:49 UTC, EMG60 commented
> Sorry, but the switches you are proposing are not correct. Even the 
> existing ones for BCC32 are wrong (ie. -w-sig- and the others) because 
> the right syntax is -w-sig, without the last minus sign.
> 
> In BCC64 the switch -Weverything is absolutely useless due to the tons 
> of warning from the BCC64 include files. Anyway, BCC32 compiles fine so 
> I would not touch it. For BCC64 I choosen what allow the compilation 
> without tones of lines of warnings. But if you really want this I can 
> put your suggested switches, no problems for me. So please confirm that 
> it is what you want.

Or, can you explain what are the exact meaning of _WARN_MAX, _WARN_YES, 
_WARN_LOW and _WARN_NO, so I can fix the code properly for BCC32 and BCC64?

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

2023-11-05 09:39 UTC, EMG60 commented
> Or, can you explain what are the exact meaning of _WARN_MAX, _WARN_YES, 
> _WARN_LOW and _WARN_NO, so I can fix the code properly for BCC32 and BCC64?

Is this the only documentation about the hbmk2 warning levels?

#define _WARN_DEF               0  /* Do not set any explicit warning 
level */
#define _WARN_MAX               1
#define _WARN_YES               2  /* Default level in Harbour build */
#define _WARN_LOW               3  /* Low level, used for 3rd party code 
in Harbour build */
#define _WARN_NO                4  /* Explicitly disable warnings */

If yes, I can do this:

- for _WARN_MAX: -Weverything plus all the flags required to suppress 
warnings from the BCC include files:

-Weverything -Wno-language-extension-token -Wno-typedef-redefinition 
-Wno-undef -Wno-unknown-pragmas -Wno-c11-extensions -Wno-visibility 
-Wno-bad-function-cast -Wno-padded -Wno-pedantic 
-Wno-missing-declarations -Wno-unreachable-code

- for _WARN_YES: as _WARN_MAX but without the warning about the sign 
conversion:

-Weverything -Wno-language-extension-token -Wno-typedef-redefinition 
-Wno-undef -Wno-unknown-pragmas -Wno-c11-extensions -Wno-visibility 
-Wno-bad-function-cast -Wno-padded -Wno-pedantic 
-Wno-missing-declarations -Wno-unreachable-code -Wno-sign-conversion

(continue...)

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

2023-11-05 10:13 UTC, EMG60 commented
> - for _WARN_YES: as _WARN_MAX but without the warning about the sign 
> conversion:
> 
> -Weverything -Wno-language-extension-token -Wno-typedef-redefinition 
> -Wno-undef -Wno-unknown-pragmas -Wno-c11-extensions -Wno-visibility 
> -Wno-bad-function-cast -Wno-padded -Wno-pedantic 
> -Wno-missing-declarations -Wno-unreachable-code -Wno-sign-conversion

Changed:

"-Weverything -Wno-language-extension-token -Wno-typedef-redefinition 
-Wno-undef -Wno-unknown-pragmas -Wno-c11-extensions -Wno-visibility 
-Wno-bad-function-cast -Wno-padded -Wno-pedantic 
-Wno-missing-declarations -Wno-unreachable-code -Wno-sign-conversion 
-Wno-missing-prototypes -Wno-comment -Wno-float-equal 
-Wno-conditional-uninitialized -Wno-cast-align -Wno-conversion 
-Wno-unused-macros -Wno-tautological-compare -Wno-format-nonliteral 
-Wno-shadow"

(continue...)

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

2023-11-05 10:17 UTC, EMG60 commented
- for _WARN_LOW only these flags:

"-Wno-typedef-redefinition -Wno-visibility -Wno-missing-declarations 
-Wno-missing-prototypes -Wno-tautological-compare"

- for _WARN_NO only this flag:

"-w"

Let me know what do you think about all of that.

2023-11-05 10:23 UTC, EMG60 commented
Please note that all the above flags are only for BCC64. Later we will 
review the flags for BCC32.

2023-11-05 15:44 UTC, EMG60 commented
Please also note that I already test with BCC 7.10 all I wrote.

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

2023-11-07 16:49 UTC, EMG60 commented
Still waiting... :-)

2023-11-08 01:11 UTC, tuffnatty commented
Hi @EMG60 ! I have done the job to the stage where I consider it completed. Please review and test with all the older compiler versions you have.

About the build warnings: as AFAICT hbmk2 is deprecated and kept in tree only because Harbour contrib building depends on it, what one needs to know is there are two levels of warnings in Harbour build, they are regulated not by user, but by HB_BUILD_WARN=no directives in some selected Makefiles for third-party code. Then, one needs to consider that bcc64 is clang in disguise, and so it accepts the same warning options as all the other gcc and clang compatible compilers. So I just took clang options for warnings and optimization.

About `xmath`: On 7.60. the code seems to work fine without any additional `xmath` library.

About codepage problems: I added a tool which converts C sources to 8-bit clean representation transparently when compiling `src/codepage` and `src/lang` under bcc64. You need to have powershell, I guess it's not a problem now. Or, it can be rewritten in C (as Harbour is definitely unavailable at the time when it's needed).

2023-11-08 09:12 UTC, EMG60 commented
Sorry, I don't understand. Please check my changes and commit it. Otherwise I can't create BCC64 build.

2023-11-08 09:23 UTC, EMG60 commented
> Hi @EMG60 <https://github.com/EMG60> ! I have done the job to the stage 
> where I consider it completed. Please review and test with all the older 
> compiler versions you have.

I can't see any new commit in the core repository. So, what do I have to 
test?

> About the build warnings: as AFAICT hbmk2 is deprecated and kept in tree 
> only because Harbour contrib building depends on it,

I didn't know it, but it is not the point of my changes. Anyway, I only 
use win-make.exe and it, in turn, uses hbmk2.exe to build the contribs. 
Are there a better official way to build Harbour? If yes, can you show 
it to me, please?

> what one needs to know is there are two levels of warnings in Harbour
> build, they are regulated not by user, but by HB_BUILD_WARN=no
> directives in some selected Makefiles for third-party code.

This I have already understood.

> Then, one needs to consider that bcc64 is clang in disguise,

It is not "in disguise", it is openly CLANG.

> and so it accepts the same warning options as all the other gcc and
> clang compatible compilers. So I just took clang options for warnings
> and optimization.

That's why I propose my current changes.

> About |xmath|: On 7.60. the code seems to work fine without any 
> additional |xmath| library.

That's not what I've found. Anyway, I will test it again.

> About codepage problems: I added a tool which converts C sources to 
> 8-bit clean representation transparently when compiling |src/codepage| 
> and |src/lang| under bcc64. You need to have powershell, I guess it's 
> not a problem now. Or, it can be rewritten in C (as Harbour is 
> definitely unavailable at the time when it's needed).

That would be great beacause at the current state we cannot use BCC64 
from 7.20 onward. Can you commit that change and explain how to build 
Harbour with BCC64 now, exactly?

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

2023-11-08 10:06 UTC, tuffnatty commented
@EMG60 My changes are in your master branch

2023-11-08 10:18 UTC, EMG60 commented
> @EMG60 <https://github.com/EMG60> My changes are in your master branch

Ok, tested with BCC64 7.60. Sorry, there are errors:

In file included from ../../../auxtif.c:34:
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1030:1: error: 
conflicting types for '__tg_promote'
_Tg_promote(unsigned int, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1029:1: note: 
previous declaration is here
_Tg_promote(int, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1031:1: error: 
conflicting types for '__tg_promote'
_Tg_promote(long, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1029:1: note: 
previous declaration is here
_Tg_promote(int, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1032:1: error: 
conflicting types for '__tg_promote'
_Tg_promote(unsigned long, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1029:1: note: 
previous declaration is here
_Tg_promote(int, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1033:1: error: 
conflicting types for '__tg_promote'
_Tg_promote(long long, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1029:1: note: 
previous declaration is here
_Tg_promote(int, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1034:1: error: 
conflicting types for '__tg_promote'
_Tg_promote(unsigned long long, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1029:1: note: 
previous declaration is here
_Tg_promote(int, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1035:1: error: 
conflicting types for '__tg_promote'
_Tg_promote(float, float);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1029:1: note: 
previous declaration is here
_Tg_promote(int, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1036:1: error: 
conflicting types for '__tg_promote'
_Tg_promote(double, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1029:1: note: 
previous declaration is here
_Tg_promote(int, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1037:1: error: 
conflicting types for '__tg_promote'
_Tg_promote(long double, long double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1029:1: note: 
previous declaration is here
_Tg_promote(int, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1039:1: error: 
conflicting types for '__tg_promote'
_Tg_promote(float _Complex, float _Complex);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1029:1: note: 
previous declaration is here
_Tg_promote(int, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1040:1: error: 
conflicting types for '__tg_promote'
_Tg_promote(double _Complex, double _Complex);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1029:1: note: 
previous declaration is here
_Tg_promote(int, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1041:1: error: 
conflicting types for '__tg_promote'
_Tg_promote(long double _Complex, long double _Complex);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
         static To __attribute__((__overloadable__)) __tg_promote(From)
                                                     ^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1029:1: note: 
previous declaration is here
_Tg_promote(int, double);
^
e:\fw\bcc64\bcc\bin\..\include\windows\crtl\math.h:1027:46: note: 
expanded from macro '_Tg_promote'
      [...]

2023-11-08 10:21 UTC, EMG60 commented
But I've already fix it in my local repository: just move #include <math.h> at the top.

2023-11-08 10:22 UTC, tuffnatty commented
@EMG60 To get rid of these errors, you will need to also apply #331, or disable building local 3rd party libs.

2023-11-08 11:09 UTC, EMG60 commented
Can you put all the fix in a single branch, please? So I can download it and test.

2023-11-08 11:37 UTC, tuffnatty commented
> Can you put all the fix in a single branch, please? So I can download it and test.

@EMG60 Try this: https://github.com/tuffnatty/harbour/tree/all-fixes-tmp

2023-11-08 11:54 UTC, EMG60 commented
Sorry, tons of

warning: unknown pragma ignored [-Wunknown-pragmas]

and then

Error: Unresolved external '_finitel' referenced from 
E:\FW\HARBOUR-ALL-FIXES-TMP\LIB\WIN\BCC64\HBCOMMON.A|hbprintf.o
Error: Unresolved external '_isnanl' referenced from 
E:\FW\HARBOUR-ALL-FIXES-TMP\LIB\WIN\BCC64\HBCOMMON.A|hbprintf.o
Error: Unresolved external '_finite' referenced from 
E:\FW\HARBOUR-ALL-FIXES-TMP\LIB\WIN\BCC64\HBCOMMON.A|hbprintf.o

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

2023-11-08 12:29 UTC, tuffnatty commented
Here, the header for these functions is: `C:\Embarcadero\Studio\22.0\include\windows\crtl\float.h`
The library file is `C:\Embarcadero\Studio\22.0\lib\win32\release\cw32.lib`.
I remember I had to set INCLUDE envvar to `C:\Embarcadero\Studio\22.0\include\windows\sdk` for some reason, maybe this helps.

2023-11-08 12:34 UTC, tuffnatty commented
What is your compiler version and C++Builder version?

2023-11-08 12:40 UTC, EMG60 commented
> Here, the header for these functions is: 
> |C:\Embarcadero\Studio\22.0\include\windows\crtl\float.h|
> The library file is |C:\Embarcadero\Studio\22.0\lib\win32\release\cw32.lib|.

This is for 32-bit. We are talking about BCC 64-bit.

> I remember I had to set INCLUDE envvar to 
> |C:\Embarcadero\Studio\22.0\include\windows\sdk| for some reason, maybe 
> this helps.

No, BCC does not recognize INLUDE envvar.

2023-11-08 12:41 UTC, EMG60 commented
> What is your compiler version and C++Builder version?

BCC 7.60 64-bit.

2023-11-08 12:53 UTC, tuffnatty commented
> This is for 32-bit. We are talking about BCC 64-bit.

Oh sorry. Still, it is there: `C:\Embarcadero\Studio\22.0\lib\win64\release\cw64.a`

2023-11-08 14:09 UTC, EMG60 commented
I suggest to add -Wno-unknown-pragmas here (bcc.mk):

CFLAGS += -W -Wall -Wno-unknown-pragmas

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

2023-11-08 14:15 UTC, tuffnatty commented
> I suggest to add -Wno-unknown-pragmas here (bcc.mk): CFLAGS += -W -Wall -Wno-unknown-pragmas
> […](#)

You see, I would like to know what are the pragmas in question and why my environment (BCC 7.60 from C++Builder 11) does not give this error.

I guess there are other differences in our environments.

2023-11-08 14:19 UTC, tuffnatty commented
> Sorry: powershell ... failed.

Usually powershell does produce very good error messages. Do you see one? Do you have powershell on your PATH (here it's included with Windows 10, I did not have to install anything)?

2023-11-08 14:27 UTC, EMG60 commented
> You see, I would like to know what are the pragmas in question and why 
> my environment (BCC 7.60 from C++Builder 11) does not give this error.

This is the first I see:

bcc64.exe   -I. -I../../../../../include -q -tWM -W -Wall -O3  -DUNICODE 
  -ohbdate.o  -c ../../../hbdate.c
../../../hbdate.c:
In file included from ../../../hbdate.c:62:
e:\fw\bcc64\bcc\bin\..\include\windows\sdk\windows.h:42:9: warning: 
unknown pragma ignored [-Wunknown-pragmas]
#pragma region Application Family or OneCore Family

> I guess there are other differences in our environments.

Can I see the batch you are using to build Harbour with BCC64?

2023-11-08 14:33 UTC, tuffnatty commented
My PATH includes bcc64.exe path, INCLUDE is C:\Embarcadero\Studio\22.0\include\windows\sdk, and then I just run:

64-bit: `win-make.exe HB_COMPILER=bcc64 HB_CPU=x86_64 HB_USER_CFLAGS=-Werror`
32-bit: `win-make.exe HB_COMPILER=bcc HB_USER_CFLAGS=-w!`

2023-11-08 14:39 UTC, EMG60 commented
> Usually powershell does produce very good error messages. Do you see 
> one? Do you have powershell on your PATH (here it's included with 
> Windows 10, I did not have to install anything)?

You are right! It wasn't in the path. Building...

2023-11-08 14:42 UTC, EMG60 commented
> You are right! It wasn't in the path. Building...

It worked. But libcurl-x64.a is missing. Can you look at it, please?

2023-11-08 14:43 UTC, EMG60 commented
> It worked. But libcurl-x64.a is missing. Can you look at it, please?

I used this workaround:

mkexp %cd%\lib\win\bcc64\libcurl-x64.a %HB_WITH_CURL%\..\bin\libcurl-x64.dll
COPY %cd%\lib\win\bcc64\libcurl-x64.a 
%HB_INSTALL_PREFIX%\lib\win\bcc64\libcurl-x64.a > NUL

2023-11-08 15:07 UTC, EMG60 commented
> My PATH includes bcc64.exe path, INCLUDE is 
> C:\Embarcadero\Studio\22.0\include\windows\sdk, and then I just run:
> 
> 64-bit: win-make.exe HB_COMPILER=bcc64 HB_CPU=x86_64 HB_USER_CFLAGS=-Werror
> 32-bit: win-make.exe HB_COMPILER=bcc HB_USER_CFLAGS=-w!

Where do I have to add the contrib paths like curl and OpenSSL? Anyway, 
with you command I still get a tons of unknown-pragmas warnings.

2023-11-08 17:14 UTC, tuffnatty commented
Contrib building:
`win-make HB_COMPILER=bcc64 HB_CPU=x86_64 HB_USER_CFLAGS=-Werror HB_BUILD_CONTRIBS=hbcurl HB_WITH_CURL=c:\curl-8.4.0_6-win64-mingw\include HB_BUILD_VERBOSE=yes -C contrib`

2023-11-08 17:56 UTC, EMG60 commented
> |#pragma region| is listed as supported in all the C++Builder docs still 
> online, that is, 10.0+ (Seattle).
> Are you sure the right bcc64.exe is used?

How to check? Can you send me your BCC64 (bin, include and lib folders)?

2023-11-08 19:23 UTC, tuffnatty commented
1. What I did is I registered at https://www.embarcadero.com/products/cbuilder/starter and downloaded it several days ago.
2. I don't mean there are right and wrong bcc64 versions for building Harbour; I only suggest that bcc64.exe you're calling is not suitable for the Windows SDK provided. Try this: 
```
Z:\harbour-src>where.exe bcc64.exe                                                                                                                              C:\Embarcadero\Studio\22.0\bin\bcc64.exe 
```

2023-11-08 22:52 UTC, EMG60 commented
> Contrib building:
> win-make HB_COMPILER=bcc64 HB_CPU=x86_64 HB_USER_CFLAGS=-Werror HB_BUILD_CONTRIBS=hbcurl HB_WITH_CURL=c:\curl-8.4.0_6-win64-mingw\include HB_BUILD_VERBOSE=yes -C contrib

As I wrote, I don't get libcurl-x64.a. Do you get it?

2023-11-08 22:59 UTC, EMG60 commented
>  2. I don't mean there are right and wrong bcc64 versions for building
>     Harbour; I only suggest that bcc64.exe you're calling is not
>     suitable for the Windows SDK provided.

Don't think so. Anyway, I suppress all that warning to speed up the 
compilation and all is OK now, except libcurl-x64.a. But I can get it 
with my workaround, no problem. So, can you commit it to main repository 
now? Only one more question: all those calls to powershell greatly slow 
down the process. Is there nothing we can do to speed up them?

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

2023-11-08 23:39 UTC, tuffnatty commented
As I already mentioned, one can rewrite the script in C or keep using bcc32, the build speed with bcc32 is amazing. Is this why people still use Borland C? Then, the switch to Clang will be disgusting.

2023-11-09 08:36 UTC, EMG60 commented
> As I already mentioned, one can rewrite the script in C or keep using 
> bcc32, the build speed with bcc32 is amazing. Is this why people still 
> use Borland C? Then, the switch to Clang will be disgusting.

Ok, don't worry. I'm waiting for the commit in the main repository. 
Thank you!

2023-11-09 08:41 UTC, EMG60 commented
> As I already mentioned, one can rewrite the script in C or keep using 
> bcc32, the build speed with bcc32 is amazing. Is this why people still 
> use Borland C? Then, the switch to Clang will be disgusting.

I switched to MSC one year ago and I'm very happy with it (fast and 
produces smaller EXEs).

2023-11-09 20:25 UTC, vszakats commented on config/win/bcc.mk
> +# As the source location changes, -I$(GRANDP) must be added as well.
It's hard to believe that a modern compiler needs a hack like that. "bcc64" is a commercial rebadge of llvm/clang, and the latter is capable of compiling UTF-8 strings with no issues by default.

According to this blog article, the relevant compiler option might be `--codepage:65001`:
https://blogs.embarcadero.com/the-delphi-compiler-and-utf-8-encoded-source-code-files-with-no-bom/

But why not use the native llvm/clang? (e.g. llvm-mingw, which has UCRT and ARM64 support out of the box, open-source, free and runs on all major platforms: https://github.com/mstorsjo/llvm-mingw/releases)

2023-11-09 20:44 UTC, EMG60 commented
> It's hard to believe that a modern compiler needs a hack like that. 
> "bcc64" is a commercial rebadge of llvm/clang, and the latter is capable 
> of compiling UTF-8 strings with no issues by default.

It's only a bug.

> According to this blog article, the relevant compiler option might be --codepage:65001:

bcc64.exe: error: unsupported option '--codepage:65001'

That article is for Delphi, if I'm not wrong.

> But why not use the native llvm/clang? (e.g. llvm-mingw, which has UCRT 
> and ARM64 support out of the box, open-source, free and runs on all 
> major platforms: https://github.com/mstorsjo/llvm-mingw/releases

I have MinGW too. I'm using only MSC now but I like to also have BCC 
working. That's all.

2023-11-09 21:24 UTC, vszakats commented
If this is a bug in bcc64, it's probably better to upgrade to a version that works correctly. Calling an embedded PowerShell script before each compiler invocation is just ...odd? If this is an unfixed bug, I'm not sure this effort to make it work is best spent, given all the well-working (and no-cost) alternatives.

Also, duplicating all (or half) the llvm/clang logic under bcc64 feels like something that will bite future maintainability. Might be more practical to make bcc64 an alias for clang64 and patch out the differences there.

2023-11-09 22:21 UTC, EMG60 commented
Il 09/11/2023 22:25, Viktor Szakats ha scritto:

> If this is a bug in bcc64, it's probably better to upgrade to a version 
> that works correctly. Calling an embedded PowerShell script before each 
> compiler invocation is just ...odd?

I agree!

-- 
Enrico Maria Giordano

http://www.emagsoftware.it
http://www.emagsoftware.it/emgmusic
http://www.emagsoftware.it/spectrum
http://www.emagsoftware.it/tbosg

2023-11-10 10:20 UTC, alcz commented
> It's hard to believe that a modern compiler needs a hack like that. "bcc64" is a commercial rebadge of llvm/clang, and the latter is capable of compiling UTF-8 strings with no issues by default.
> It's only a bug.
> According to this blog article, the relevant compiler option might be --codepage:65001:
> bcc64.exe: error: unsupported option '--codepage:65001' That article is for Delphi, if I'm not wrong.

http://docwiki.embarcadero.com/RADStudio/Seattle/en/C%2B%2B_Compiler_Advanced#Other_Options
-CP65001 seems like an option, but why would it do something and what is it for? changing behaviour of C RTL functions like strlen() on unprefixed char array literals seems quite mad

2023-11-10 10:29 UTC, EMG60 commented
> -CP65001 seems like an option,

No, it is only for BCC32.

2023-11-11 21:04 UTC, tuffnatty commented
> If this is a bug in bcc64, it's probably better to upgrade to a version that works correctly.

There is none yet.

> Calling an embedded PowerShell script before each compiler invocation is just ...odd?

It's switched on only for src/lang/ and src/codepage/ where we do have 8-bit-high C literals.
If a person who cares rewrites the conversion in C it will be not that slow.
 
> If this is an unfixed bug, I'm not sure this effort to make it work is best spent, given all the well-working (and no-cost) alternatives.

The effort is already spent. Personally I after learning about this bug will try to forget this compiler as a nightmare.

> Also, duplicating all (or half) the llvm/clang logic under bcc64 feels like something that will bite future maintainability. Might be more practical to make bcc64 an alias for clang64 and patch out the differences there.

There's not so much logic duplicated with clang, only optimization and warning flags. The libraries have .a suffix and no prefix, and tlib / ilink are used for linking and archiving. Sure something could be factored better, but at this level it won't be worth the effort.

2023-11-11 21:26 UTC, vszakats commented
What is exactly the problem Borland/Embarcadero C++ is solving nowadays compared to high quality FLOSS/no cost compilers like llvm, gcc or msvc?

2023-11-13 17:15 UTC, tuffnatty commented
> > It worked. But libcurl-x64.a is missing. Can you look at it, please?
> 
> I find the culprit: it was the file libcurl-x64.def that prevented the creation of libcurl-x64.a. I deleted that file and now all is fine.

Yes, I also have added to hbmk locally some support for `mkexp` not recognizing `libcurl-x64.def`, but I am really unsure this file is valid (it has no LIBRARY clause); in any case, hbmk could do a better job and retry with `.a` or `.dll` if `.def` fails.

2023-11-15 13:35 UTC, alcz commented
> What is exactly the problem Borland/Embarcadero C++ is solving nowadays compared to high quality FLOSS/no cost compilers like llvm, gcc or msvc?

I guess the only highlight feature of it is that one can use Delphi VCL based UI from C/C++ language. Not looking important in pure Harbour developement environment.

2023-12-23 14:03 UTC, closed without merging